apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dev-pacman-hpa                  # HPA 이름
  namespace: pacman
spec:
  scaleTargetRef:                       # 스케일 대상
    apiVersion: apps/v1
    kind: Deployment
    name: dev-pacman                    # 실제 배포된 Deployment 이름
  minReplicas: 3                        # 최소 파드 수
  maxReplicas: 5                        # 최대 파드 수
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50          # 평균 CPU 사용률 50% 넘으면 확장