apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacman
  labels:
    app: pacman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pacman
  template:
    metadata:
      labels:
        app: pacman
    spec:
      containers:
      - name: pacman
        image: dbafromthecold/pac-man:latest   # 실습용 Pac-Man 웹게임 이미지
        # 만약 Pull 오류가 나면 예비 이미지로 교체:
        # image: alexwhen/docker-2048:latest  # (임시 대체: 2048 게임)
        ports:
        - containerPort: 80
        # 단순 정적 서버라 별도 헬스엔드포인트가 없을 수 있어 아래처럼 완만하게
        readinessProbe:
          httpGet: { path: "/", port: 80 }
          initialDelaySeconds: 3
          periodSeconds: 10
        livenessProbe:
          httpGet: { path: "/", port: 80 }
          initialDelaySeconds: 10
          periodSeconds: 20
