apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  namespace: guestbook
spec:
  type: NodePort
  selector:
    app: guestbook-ui    # 반드시 Guestbook의 라벨과 맞춰야 함
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
