apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    targetRevision: 15.10.0
    helm:
      releaseName: nginx-helm
      values: |
        service:
          type: NodePort
          nodePorts:
            http: 30081      
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
