apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: 17.11.3
    helm:
      releaseName: redis-helm
      values: |
        master:
          persistence:
            enabled: true
            storageClass: "local-path"
        replica:
          persistence:
            enabled: true
            storageClass: "local-path"
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
